name: Deploy Next.js App portfolio
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "RESUME_DRIVE_LINK=${{secrets.RESUME_DRIVE_LINK}}" >> .env && echo "EMAIL_USER=${{secrets.EMAIL_USER}}" >> .env && echo "EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}" >> .env && echo "EMAIL_USER_SEND_TO=${{secrets.EMAIL_USER_SEND_TO}}" >> .env
      - name: Buildnext.js app
        run: |
          npm install
          npm run build
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "RESUME_DRIVE_LINK=${{secrets.RESUME_DRIVE_LINK}}" >> .env && echo "EMAIL_USER=${{secrets.EMAIL_USER}}" >> .env && echo "EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}" >> .env && echo "EMAIL_USER_SEND_TO=${{secrets.EMAIL_USER_SEND_TO}}" >> .env
    
      - name: Install dependencies
        run: npm install
        
      - name: Restart app with PM2
        run: |
          pm2 delete portfolio || true
          pm2 start npm --name "portfolio" -- run start
